n1=int(input('digite um numero inteiro'))
n2=int(input('digite um numero inteiro'))
n3=int(input('digite um numero real'))
p=(n1*2)*(n2/2)
print('o produto do dobro do primeiro com a metade do segundo é {}'.format(p))